# Generated by Django 6.0.6 on 2026-07-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_area_order_building_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='unknnown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('COD', 'COD')], default='COD', max_length=50),
        ),
    ]
