# Generated by Django 6.0.6 on 2026-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
